import type { NextPage } from 'next';
import Head from 'next/head';

import { Layout, Container, Footer, ContactForm } from 'components';

const ContactPage: NextPage = () => {
  return (
    <Layout preview={false}>
      <Head>
        <title>Whero</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <h1>Contact</h1>
        <ContactForm />
      </Container>

      <Footer />
    </Layout>
  );
};

export default ContactPage;
