name: Create release candidate ✨
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: Type of release
        required: true
        default: release patch
        type: choice
        options:
          - release major
          - release minor
          - release patch
jobs:
  create-release-candidate:
    runs-on: ubuntu-20.04
    steps:
    - name: Set major release
      if: ${{ github.event.inputs.release_type == 'release major' }}
      run: echo "RELEASE=major" >> ${GITHUB_ENV}
    - name: Set minor release
      if: ${{ github.event.inputs.release_type == 'release minor' }}
      run: echo "RELEASE=minor" >> ${GITHUB_ENV}
    - name: Set patch release
      if: ${{ github.event.inputs.release_type == 'release patch' }}
      run: echo "RELEASE=patch" >> ${GITHUB_ENV}
    - name: Check out code
      uses: actions/checkout@v2
      with:
        ref: deploy-production
    - name: Set release date
      run: |
        echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
    - name: Reset promotion branch
      run: |
        git fetch origin main:main
        git reset --hard main
    - name: Bump package version
      run: |
        yarn version --${{ env.RELEASE }} --no-git-tag-version
    - name: Render template
      id: template
      uses: chuhlomin/render-template@v1.4
      with:
        template: .github/PULL_REQUEST_TEMPLATE.md
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        title: Release | ${{ env.RELEASE_DATE }}
        body: ${{ steps.template.outputs.result }}
        commit-message: Bump version ${{ env.RELEASE }}
        committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
        assignees: ${{ github.event.sender.login }}
        reviewers: ${{ github.event.sender.login }}
        labels: ${{ github.event.inputs.release_type }}
        branch: release/${{ env.RELEASE_DATE }}
        base: deploy-production
        delete-branch: true
